name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r * ec2-user@16.171.113.27:~/MastersProjectCode/

      - name: Install dependencies and restart Flask app
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@16.171.113.27 << 'EOF'
          cd ~/MastersProjectCode
          source venv/bin/activate
          pip install -r requirements.txt
          pkill gunicorn || true
          nohup gunicorn -b 0.0.0.0:80 app:app &
          EOF
